优化语法

diff --git a/.github/workflows/rr.yml b/.github/workflows/rr.yml
--- a/.github/workflows/rr.yml
+++ b/.github/workflows/rr.yml
@@ -43,8 +43,12 @@ jobs:
           sudo timedatectl set-timezone "Asia/Shanghai"
 
           sudo apt update
-          sudo apt install -y jq cpio gettext
-          sudo snap install yq
+          sudo apt install -y locales busybox dialog gettext sed gawk jq curl 
+          sudo apt install -y python-is-python3 python3-pip libelf-dev qemu-utils cpio xz-utils lz4 lzma bzip2 gzip zstd
+          # sudo snap install yq
+          if ! command -v yq &>/dev/null || ! yq --version 2>/dev/null | grep -q "v4."; then
+            sudo curl -kL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/bin/yq && sudo chmod a+x /usr/bin/yq
+          fi
 
       # calculates the version number and push
       - name: Calculate version
@@ -58,7 +62,7 @@ jobs:
               VERSION="${{ inputs.version }}"
             else
               LATEST_TAG="$(curl -skLH "Authorization: token ${{ secrets.RRORG }}" "https://api.github.com/repos/RROrg/rr/releases" | jq -r ".[0].tag_name" 2>/dev/null)"
-              if [ -n "${LATEST_TAG}" -a "$(echo ${LATEST_TAG} | cut -d '.' -f 1,2)" = "$(date +'%y.%-m')" ]; then  # format %y.%-m.$i
+              if [ -n "${LATEST_TAG}" ] && [ "$(echo ${LATEST_TAG} | cut -d '.' -f 1,2)" = "$(date +'%y.%-m')" ]; then  # format %y.%-m.$i
                 VERSION="$(echo ${LATEST_TAG} | awk -F '.' '{$3=$3+1}1' OFS='.')"
               else
                 VERSION="$(date +'%y.%-m').0"
@@ -73,9 +77,8 @@ jobs:
           echo "TAGDATE=${TAGDATE}" >>$GITHUB_ENV
           echo "VERSION=${VERSION}" >>$GITHUB_ENV
 
+          cd rr
           if [ -n "${VERSION}" ]; then
-            cd rr
-
             # Modify Source File
             echo "${VERSION}" >VERSION
             echo "${VERSION}" >files/mnt/p1/RR_VERSION
@@ -90,10 +93,9 @@ jobs:
               git push -f
             fi
           else
-            cd rr
-
             sed -i "s/^RR_VERSION=.*$/RR_VERSION=\"${TAGDATE}\"/" files/initrd/opt/rr/include/consts.sh
           fi
+          cd -
 
       # Convert po2mo, Get exts
       - name: Convert po2mo, Get extractor, LKMs, addons and Modules
@@ -126,30 +128,39 @@ jobs:
           . scripts/func.sh "${{ secrets.RRORG }}"
 
           echo "Create RR_1GB image"
-          gzip -dc "files/initrd/opt/rr/grub.img.gz" >"rr_1GB.img"
-          fdisk -l "rr_1GB.img"
+          IMAGE_FILE="rr_1GB.img"
+          gzip -dc "files/initrd/opt/rr/grub.img.gz" >"${IMAGE_FILE}"
+          fdisk -l "${IMAGE_FILE}"
 
           LOOPX=$(sudo losetup -f)
-          sudo losetup -P "${LOOPX}" "rr_1GB.img"
+          sudo losetup -P "${LOOPX}" "${IMAGE_FILE}"
 
-          echo "Mounting image file"
-          mkdir -p "/tmp/p1"
-          mkdir -p "/tmp/p3"
-          sudo mount ${LOOPX}p1 "/tmp/p1"
-          sudo mount ${LOOPX}p3 "/tmp/p3"
+          for i in {1..3}; do
+            [ ! -d "files/mnt/p${i}" ] && continue
+            
+            rm -rf "/tmp/mnt/p${i}"
+            mkdir -p "/tmp/mnt/p${i}"
 
-          echo "Copying files"
-          sudo cp -Rf "files/mnt/p1/"* "/tmp/p1"
-          sudo cp -Rf "files/mnt/p3/"* "/tmp/p3"
-          sync
+            echo "Mounting ${LOOPX}p${i}"
+            sudo mount "${LOOPX}p${i}" "/tmp/mnt/p${i}" || {
+              echo "Can't mount ${LOOPX}p${i}."
+              break
+            }
+            echo "Copying files to ${LOOPX}p${i}"
+            [ ${i} -eq 1 ] && sudo cp -af "files/mnt/p${i}/"{.locale,.timezone} "/tmp/mnt/p${i}/" 2>/dev/null || true
+            sudo cp -rf "files/mnt/p${i}/"* "/tmp/mnt/p${i}" || true
 
-          echo "Unmount image file"
-          sudo umount "/tmp/p1"
-          sudo umount "/tmp/p3"
-          rmdir "/tmp/p1"
-          rmdir "/tmp/p3"
+            sudo sync
 
-          sudo losetup --detach ${LOOPX}
+            echo "Unmounting ${LOOPX}p${i}"
+            sudo umount "/tmp/mnt/p${i}" || {
+              echo "Can't umount ${LOOPX}p${i}."
+              break
+            }
+            rm -rf "/tmp/mnt/p${i}"
+          done
+
+          sudo losetup --detach "${LOOPX}"
 
           echo "Create RR_4GB image" # $((1024 * 3 - 512))
           resizeImg "rr_1GB.img" "+2560M" "rr.img"
@@ -186,7 +197,7 @@ jobs:
               (cd $(dirname "${F}") && sha256sum $(basename "${F}")) >>sha256sum
               zip -9j "update-${VERSION}.zip" "${F}"
             fi
-          done < <(yq '.replace | explode(.) | to_entries | map([.key])[] | .[]' update-list.yml)
+          done <<<$(yq '.replace | explode(.) | to_entries | map([.key])[] | .[]' update-list.yml)
           zip -9j "update-${VERSION}.zip" sha256sum
 
           # updateall.zip
@@ -208,7 +219,7 @@ jobs:
               (cd $(dirname "${F}") && sha256sum $(basename "${F}")) >>sha256sum
               zip -9j "updateall-${VERSION}.zip" "${F}"
             fi
-          done < <(yq '.replace | explode(.) | to_entries | map([.key])[] | .[]' update-list.yml)
+          done <<<$(yq '.replace | explode(.) | to_entries | map([.key])[] | .[]' update-list.yml)
           zip -9j "updateall-${VERSION}.zip" sha256sum
 
           # sha256sum
